### PR TITLE
Add search by zipcode

### PR DESCRIPTION
**Pull request by nambrot**
This PR adds the ability to search by zip code

### CODE REVIEW

**Comment by edoshor** [comment]
There are 2 points we can think about:
- Zip code by itself is not enough for an Address to be searchable. It needs to be accompanied with at least country or state & city.
- Sure we can check this easily. However, this is the "quick" way to construct queries. 
  We suggest you construct the Person object yourself as it allows for greater flexibility.

**Comment by nambrot** [comment]
Interesting, it is not clear from the docs that zipcode by itself isn't enough (although I guess if you think about it, it does make sense.

Do you have a preferred means of doing so?

**Comment by nambrot** [comment]
Interestingly in my sample requests, adding a zipcode did in fact change the search results and promoted the relevant possible people. Is that just co-incidence?

**Comment by edoshor** [comment]
No co-incidence. Adding a zip_code to an Address is a great help for our search engine. In fact, every piece of information you send helps our engine to come up with better, more accurate, results. 

The preferred way for making advanced queries is to construct the Person object yourself. 
So instead of passing separated fields and let the library construct the Person object for you:

``` ruby
Pipl::client.search raw_name: 'Clark Kent', 
                    country: 'US', state: 'AZ', city: 'Phoenix', zip_code: '85001'
```

You simply pass a person object yourself:

``` ruby
Pipl::client.search person: Pipl::Person.new(fields: [
    Pipl::Name.new(raw: 'Clark Kent'),
    Pipl::Address.new(country: 'US', state: 'AZ', city: 'Phoenix', zip_code: '85001')
])
```

**Pull request closed without merging**
